import 'models.dart';

final List<AppInfo> inforttsCatalog = [
  // 🟢 Live Internal Testing Apps
  const AppInfo(
    slug: 'cardiodictyon',
    name: 'Cardiodictyon Mobile',
    tagline: 'Autonomous swarm telemetry & node control',
    description: 'Autonomous swarm telemetry, cluster monitoring, and device control node.',
    iconUrl: 'https://cdn.infortts.site/icons/cardiodictyon.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701570838917970273',
    repoPath: 'projects/cardiodictyon',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/internaltest/4701570838917970273',
        sha256: '',
        sizeBytes: 52533657,
        releaseNotes: 'Initial production build for Google Play internal testing.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'cyclomedusa',
    name: 'Cyclomedusa AR',
    tagline: 'Spatial neural mapping & perceptual compute',
    description: 'Spatial neural mapping, augmented reality sensors, and perceptual compute.',
    iconUrl: 'https://cdn.infortts.site/icons/cyclomedusa.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701318995429644311',
    repoPath: 'projects/cyclomedusa',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/internaltest/4701318995429644311',
        sha256: '',
        sizeBytes: 51485081,
        releaseNotes: 'Spatial mapping pipeline release.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'dickinsonia',
    name: 'Dickinsonia',
    tagline: 'Distributed content-addressable storage fabric',
    description: 'Distributed content-addressable storage fabric and memory synchronization node.',
    iconUrl: 'https://cdn.infortts.site/icons/dickinsonia.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701074981878644468',
    repoPath: 'projects/dickinsonia',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/internaltest/4701074981878644468',
        sha256: '',
        sizeBytes: 54211379,
        releaseNotes: 'Storage fabric cluster sync.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'ernietta',
    name: 'Ernietta',
    tagline: 'Sub-millisecond mesh routing & edge gateways',
    description: 'Sub-millisecond mesh routing, cross-cluster peering, and edge gateways.',
    iconUrl: 'https://cdn.infortts.site/icons/ernietta.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701202267214643622',
    repoPath: 'projects/ernietta',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/internaltest/4701202267214643622',
        sha256: '',
        sizeBytes: 51800000,
        releaseNotes: 'Mesh gateway release.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'fractofusus',
    name: 'Fractofusus',
    tagline: 'Self-replicating task distribution matrix',
    description: 'Self-replicating task distribution, agent coordination, and compute scheduling.',
    iconUrl: 'https://cdn.infortts.site/icons/fractofusus.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701532130739943923',
    repoPath: 'projects/fractofusus',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/internaltest/4701532130739943923',
        sha256: '',
        sizeBytes: 54000000,
        releaseNotes: 'Swarm coordinator build.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'ikaria',
    name: 'Ikaria',
    tagline: 'Evolutionary algorithm runner & bio-compute',
    description: 'Evolutionary algorithm runner, genetic compute workloads, and simulation matrix.',
    iconUrl: 'https://cdn.infortts.site/icons/ikaria.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701698683636108581',
    repoPath: 'projects/ikaria',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/internaltest/4701698683636108581',
        sha256: '',
        sizeBytes: 52300000,
        releaseNotes: 'Bio-compute release build.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'meeseeks',
    name: 'Meeseeks OS Mobile',
    tagline: 'Autonomous multi-agent terminal & voice assistant',
    description: 'Autonomous goal-driven multi-agent command interface and interactive voice terminal.',
    iconUrl: 'https://cdn.infortts.site/icons/meeseeks.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701299605514848597',
    repoPath: 'projects/meeseeks',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/internaltest/4701299605514848597',
        sha256: '',
        sizeBytes: 52700000,
        releaseNotes: 'Autonomous agent runtime release.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'mitochondria',
    name: 'Mitochondria Terminal',
    tagline: 'Core container lifecycle & power orchestrator',
    description: 'Primary energy management, container engine lifecycle, and power orchestrator.',
    iconUrl: 'https://cdn.infortts.site/icons/mitochondria.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701690297526834866',
    repoPath: 'projects/mitochondria',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/internaltest/4701690297526834866',
        sha256: '',
        sizeBytes: 53700000,
        releaseNotes: 'Core power node release.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'opabinia',
    name: 'Opabinia',
    tagline: '5-stream sensory ingestion & optical telemetry',
    description: '5-stream sensory ingestion pipeline, real-time video inference, and optical telemetry.',
    iconUrl: 'https://cdn.infortts.site/icons/opabinia.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701285546372048102',
    repoPath: 'projects/opabinia',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/internaltest/4701285546372048102',
        sha256: '',
        sizeBytes: 53000000,
        releaseNotes: 'Optical stream processor.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'orthrozanclus',
    name: 'Orthrozanclus',
    tagline: 'Zero-trust defensive boundary monitor',
    description: 'Defensive boundary monitoring, zero-trust cryptographic enforcement, and threat mitigation.',
    iconUrl: 'https://cdn.infortts.site/icons/orthrozanclus.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701235294408545779',
    repoPath: 'projects/orthrozanclus',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/internaltest/4701235294408545779',
        sha256: '',
        sizeBytes: 54000000,
        releaseNotes: 'Zero trust boundary protection release.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'tridrishti',
    name: 'Tridrishti Vision',
    tagline: 'Tri-focal stereo vision pipeline & depth compute',
    description: 'Tri-focal stereo vision pipeline and autonomous depth compute node.',
    iconUrl: 'https://cdn.infortts.site/icons/tridrishti.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701589301153857373',
    repoPath: 'projects/tridrishti',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/internaltest/4701589301153857373',
        sha256: '',
        sizeBytes: 54500000,
        releaseNotes: 'Stereo vision release build.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'yorgia',
    name: 'Yorgia',
    tagline: 'Planar parallel cellular automaton engine',
    description: 'Massive parallel tile computation engine and cellular automaton matrix.',
    iconUrl: 'https://cdn.infortts.site/icons/yorgia.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701334502307777183',
    repoPath: 'projects/yorgia',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/internaltest/4701334502307777183',
        sha256: '',
        sizeBytes: 53000000,
        releaseNotes: 'Parallel tile engine release.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  // 📦 New Ecosystem Nodes with Direct Opt-In URLs
  const AppInfo(
    slug: 'charnia',
    name: 'Charnia',
    tagline: 'Corporate registry & governance dispatcher',
    description: 'Central operational legal registry, organizational hierarchy, and governance dispatcher.',
    iconUrl: 'https://cdn.infortts.site/icons/charnia.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
    repoPath: 'projects/charnia',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
        sha256: '',
        sizeBytes: 45600000,
        releaseNotes: 'Corporate registry release.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'cloudina',
    name: 'Cloudina',
    tagline: 'Financial ledger & operations system',
    description: 'Immutable double-entry financial ledger, billing automation, and compliance accounting.',
    iconUrl: 'https://cdn.infortts.site/icons/cloudina.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
    repoPath: 'projects/cloudina',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
        sha256: '',
        sizeBytes: 45600000,
        releaseNotes: 'Financial ledger release.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'dropship',
    name: 'Dropship',
    tagline: 'AI-powered eCommerce storefront & inventory',
    description: 'AI-driven decentralized merchant hub, inventory routing, and digital storefront.',
    iconUrl: 'https://cdn.infortts.site/icons/dropship.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
    repoPath: 'projects/dropship',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
        sha256: '',
        sizeBytes: 45600000,
        releaseNotes: 'eCommerce merchant client release.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'microdictyon',
    name: 'Microdictyon',
    tagline: 'High-frequency telemetry & rate-limiter',
    description: 'High-frequency telemetry aggregation, resource rate-limiting, and meter gateway.',
    iconUrl: 'https://cdn.infortts.site/icons/microdictyon.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
    repoPath: 'projects/microdictyon',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
        sha256: '',
        sizeBytes: 45600000,
        releaseNotes: 'Usage quota node release.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'spriggina',
    name: 'Spriggina',
    tagline: 'Biometric identity passport & profile dispatch',
    description: 'Biometric identity passport, user auth synchronization, and MCP profile dispatch.',
    iconUrl: 'https://cdn.infortts.site/icons/spriggina.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
    repoPath: 'projects/spriggina',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
        sha256: '',
        sizeBytes: 45600000,
        releaseNotes: 'Identity sync release.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'tribrachidium',
    name: 'Tribrachidium',
    tagline: 'Dynamic UI component tokens & theme registry',
    description: 'Dynamic UI component tokens, design-system synchronization, and theme registry.',
    iconUrl: 'https://cdn.infortts.site/icons/tribrachidium.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
    repoPath: 'projects/tribrachidium',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
        sha256: '',
        sizeBytes: 45600000,
        releaseNotes: 'Design token registry release.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'trilobite',
    name: 'Trilobite',
    tagline: 'Automated CI/CD build recipe validation',
    description: 'Automated CI/CD orchestration, build recipe validation, and package repository.',
    iconUrl: 'https://cdn.infortts.site/icons/trilobite.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
    repoPath: 'projects/trilobite',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
        sha256: '',
        sizeBytes: 45600000,
        releaseNotes: 'CI/CD runner release.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'wiwaxia',
    name: 'Wiwaxia',
    tagline: 'Responsive client shells & mobile viewports',
    description: 'Responsive web frontend bridge, decentralized client shells, and mobile viewports.',
    iconUrl: 'https://cdn.infortts.site/icons/wiwaxia.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
    repoPath: 'projects/wiwaxia',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
        sha256: '',
        sizeBytes: 45600000,
        releaseNotes: 'Client surface release.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'hallucigenia',
    name: 'Hallucigenia',
    tagline: 'Decentralized audio library & metadata streaming',
    description: 'Decentralized audio library, music metadata streaming, and track asset storage node.',
    iconUrl: 'https://cdn.infortts.site/icons/hallucigenia.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
    repoPath: 'projects/hallucigenia',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
        sha256: '',
        sizeBytes: 45600000,
        releaseNotes: 'Audio library release build.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'lexi',
    name: 'Lexi AI',
    tagline: 'Neural reasoning & code intelligence terminal',
    description: 'High-speed reasoning assistant, code intelligence terminal, and contextual analyzer.',
    iconUrl: 'https://cdn.infortts.site/icons/lexi.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
    repoPath: 'projects/lexi',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
        sha256: '',
        sizeBytes: 52900000,
        releaseNotes: 'Neural assistant release.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'cursus',
    name: 'Cursus',
    tagline: 'Interactive LMS & lab client',
    description: 'Intelligent course platform, technical certification runner, and interactive lab client.',
    iconUrl: 'https://cdn.infortts.site/icons/cursus.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
    repoPath: 'projects/cursus',
    latest: {'android': '1.0.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.0.0',
        downloadUrl: 'https://play.google.com/apps/testing/com.infortts.yorgia',
        sha256: '',
        sizeBytes: 52400000,
        releaseNotes: 'LMS mobile client release.',
        publishedAt: '2026-08-25T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
];
