import 'models.dart';

final List<AppInfo> inforttsCatalog = [
  const AppInfo(
    slug: 'waptia',
    name: 'Waptia Store',
    packageName: 'com.infortts.waptia',
    category: 'Infrastructure',
    tagline: 'Autonomous package manager and app distribution node for the swarm.',
    description: 'Waptia Store is the decentralized app marketplace, OTA distribution registry, and package verification hub for the entire Infortts ecosystem. It manages APK binaries, signature validation, update channels, and telemetry reporting.',
    iconUrl: 'https://cdn.infortts.site/icons/waptia.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4973664254685278609',
    repoPath: 'projects/waptia',
    latest: {'android': '2.07.01'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '2.07.01',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/waptia/waptia.apk',
        sha256: '',
        sizeBytes: 55000000,
        releaseNotes: [
          '✓ In-App Package Install Settings: One-tap button to configure Android Unknown Apps permission',
          '✓ Native in-app APK installer with FileProvider (Zero browser redirects)',
          '✓ Direct background download progress & system notifications'
        ],
        publishedAt: '2026-10-06T12:00:00Z',
        buildNumber: 20701,
      ),
    ],
  ),
  const AppInfo(
    slug: 'cardiodictyon',
    name: 'Cardiodictyon Mobile',
    packageName: 'com.infortts.cardiodictyon',
    category: 'Analytics',
    tagline: 'Swarm telemetry and autonomous device control node.',
    description: 'Cardiodictyon Mobile provides unified hardware and container telemetry across high-density distributed nodes. It aggregates CPU metrics, thermal signatures, packet latency, and device status into a real-time reactive telemetry bus with sub-10ms pub-sub performance.',
    iconUrl: 'https://cdn.infortts.site/icons/cardiodictyon.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701570838917970273',
    repoPath: 'projects/cardiodictyon',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/cardiodictyon/cardiodictyon.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'cyclomedusa',
    name: 'Cyclomedusa AR',
    packageName: 'com.infortts.cyclomedusa',
    category: 'Creative & Media',
    tagline: 'Classifies hand shapes on-device and anchors AR scenes in 3D space.',
    description: 'Cyclomedusa AR is a spatial computing and perception engine designed for on-device neural vision. It executes real-time 3D hand tracking, volumetric depth estimation, and persistent spatial anchor mapping without transmitting camera feeds off-device.',
    iconUrl: 'https://cdn.infortts.site/icons/cyclomedusa.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701318995429644311',
    repoPath: 'projects/cyclomedusa',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/cyclomedusa/cyclomedusa.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'dickinsonia',
    name: 'Dickinsonia',
    packageName: 'com.infortts.dickinsonia',
    category: 'Analytics',
    tagline: 'Content-addressed storage that syncs memory across mesh nodes.',
    description: 'Dickinsonia is an immutable, content-addressed storage engine designed for planetary-scale mesh synchronization. It deduplicates file chunks with BLAKE3 hashing, builds Merkle DAGs, and guarantees zero data loss across intermittently connected mesh networks.',
    iconUrl: 'https://cdn.infortts.site/icons/dickinsonia.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701074981878644468',
    repoPath: 'projects/dickinsonia',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/dickinsonia/dickinsonia.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'ernietta',
    name: 'Ernietta',
    packageName: 'com.infortts.ernietta',
    category: 'Infrastructure',
    tagline: 'Routes encrypted, short messages peer-to-peer with no central inbox.',
    description: 'Ernietta is a decentralized, ephemeral messaging fabric that enables zero-metadata peer-to-peer communications. It implements onion-routed forward secrecy, ensuring that messages cannot be intercepted, logged, or correlated by intermediate relay nodes.',
    iconUrl: 'https://cdn.infortts.site/icons/ernietta.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701202267214643622',
    repoPath: 'projects/ernietta',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/ernietta/ernietta.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'fractofusus',
    name: 'Fractofusus',
    packageName: 'com.infortts.fractofusus',
    category: 'Multi-Agent AI',
    tagline: 'Splits large jobs, coordinates agents, and schedules compute across nodes.',
    description: 'Fractofusus is a distributed DAG scheduler and compute orchestrator. It divides complex AI training, backtesting, and scientific simulation jobs into micro-tasks, distributing them dynamically across GPU clusters, edge servers, and mobile compute units.',
    iconUrl: 'https://cdn.infortts.site/icons/fractofusus.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701532130739943923',
    repoPath: 'projects/fractofusus',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/fractofusus/fractofusus.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'ikaria',
    name: 'Ikaria',
    packageName: 'com.infortts.ikaria',
    category: 'Infrastructure',
    tagline: 'AI-driven job crawler, auto-apply workflow & LinkedIn career optimizer with Glycocalyx RBAC.',
    description: 'Ikaria is an autonomous career accelerator and profile synchronizer. It continuously scrapes jobs across LinkedIn, WeWorkRemotely, Hirist, Naukri, and Indeed, tailors applications to candidate resumes, and orchestrates live LinkedIn profile updates.',
    iconUrl: 'https://cdn.infortts.site/icons/ikaria.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701698683636108581',
    repoPath: 'projects/ikaria',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/ikaria/ikaria.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'meeseeks',
    name: 'Meeseeks OS Mobile',
    packageName: 'com.infortts.meeseeks',
    category: 'Multi-Agent AI',
    tagline: 'Goal-driven multi-agent assistant — plain language instructions, autonomous execution.',
    description: 'Meeseeks OS is an autonomous multi-agent task execution system. Given high-level natural language goals, it provisions specialized sub-agents, writes code, queries databases, executes terminal commands, and resolves complex technical workflows autonomously.',
    iconUrl: 'https://cdn.infortts.site/icons/meeseeks.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701299605514848597',
    repoPath: 'projects/meeseeks',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/meeseeks/meeseeks.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'mitochondria',
    name: 'Mitochondria Terminal',
    packageName: 'com.infortts.mitochondria',
    category: 'Trading & FinTech',
    tagline: 'Manages container lifecycles and energy budgets for the swarm.',
    description: 'Mitochondria Terminal is the central nervous system of Infortts infrastructure. It provides low-latency interactive shells, real-time Docker/container orchestration, cluster health monitoring, and system metrics visualization across all server clusters.',
    iconUrl: 'https://cdn.infortts.site/icons/mitochondria.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701690297526834866',
    repoPath: 'projects/mitochondria',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/mitochondria/mitochondria.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'opabinia',
    name: 'Opabinia Vision',
    packageName: 'com.infortts.opabinia',
    category: 'Creative & Media',
    tagline: 'Ingests five video and sensor streams at once for real-time inference.',
    description: 'Opabinia Vision is a multi-camera perceptual processing system that fuses five simultaneous video and infrared streams into a coherent 3D perception manifold. It detects anomalies, tracks objects, and classifies events in real time.',
    iconUrl: 'https://cdn.infortts.site/icons/opabinia.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701285546372048102',
    repoPath: 'projects/opabinia',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/opabinia/opabinia.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'orthrozanclus',
    name: 'Orthrozanclus',
    packageName: 'com.infortts.orthrozanclus',
    category: 'Security & IAM',
    tagline: 'Enforces zero-trust boundaries and monitors defensive perimeters.',
    description: 'Orthrozanclus is an automated cybersecurity monitoring and zero-trust perimeter defense suite. It inspects network traffic packets, blocks intrusion attempts, manages encrypted API keys, and audits authentication compliance in real time.',
    iconUrl: 'https://cdn.infortts.site/icons/orthrozanclus.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701235294408545779',
    repoPath: 'projects/orthrozanclus',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/orthrozanclus/orthrozanclus.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'tridrishti',
    name: 'Tridrishti Vision',
    packageName: 'com.infortts.tridrishti',
    category: 'Creative & Media',
    tagline: 'Computes real-time depth from a tri-focal stereo rig.',
    description: 'Tridrishti Vision leverages tri-camera optical parallax to compute millimeter-accurate depth maps and point clouds at 60 FPS on standard smartphone hardware.',
    iconUrl: 'https://cdn.infortts.site/icons/tridrishti.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701589301153857373',
    repoPath: 'projects/tridrishti',
    latest: {'android': '1.1.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.1.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/tridrishti/tridrishti.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'yorgia',
    name: 'Yorgia',
    packageName: 'com.infortts.yorgia',
    category: 'Infrastructure',
    tagline: 'Parallel tile computation for cellular automata and heavy numeric grids.',
    description: 'Yorgia is a planar computation engine designed for massive 2D matrix transformations, discrete lattice simulations, and fast mathematical tensor operations across parallel GPU warps.',
    iconUrl: 'https://cdn.infortts.site/icons/yorgia.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701334502307777183',
    repoPath: 'projects/yorgia',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/yorgia/yorgia.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'charnia',
    name: 'Charnia',
    packageName: 'com.infortts.charnia',
    category: 'Infrastructure',
    tagline: 'One ledger for org hierarchy, registries, and governance dispatch.',
    description: 'Charnia provides an immutable organizational ledger for managing entity hierarchies, access policies, resource allocation, and verified voting records.',
    iconUrl: 'https://cdn.infortts.site/icons/charnia.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.charnia',
    repoPath: 'projects/charnia',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/charnia/charnia.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'cloudina',
    name: 'Cloudina',
    packageName: 'com.infortts.cloudina',
    category: 'Trading & FinTech',
    tagline: 'Immutable double-entry ledger with automated billing and audit history.',
    description: 'Cloudina is an enterprise double-entry accounting and financial ledger engine with automatic cryptographic reconciliations and real-time audit verification.',
    iconUrl: 'https://cdn.infortts.site/icons/cloudina.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.cloudina',
    repoPath: 'projects/cloudina',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/cloudina/cloudina.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'dropship',
    name: 'Dropship',
    packageName: 'com.infortts.dropship',
    category: 'Trading & FinTech',
    tagline: 'Routes inventory and runs storefronts from a single merchant hub.',
    description: 'Dropship is an autonomous e-commerce logistics and fulfillment engine that synchronizes multi-channel inventory, coordinates supplier dispatch, and processes orders.',
    iconUrl: 'https://cdn.infortts.site/icons/dropship.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.dropship',
    repoPath: 'projects/dropship',
    latest: {'android': '1.1.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.1.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/dropship/dropship.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'microdictyon',
    name: 'Microdictyon',
    packageName: 'com.infortts.microdictyon',
    category: 'Analytics',
    tagline: 'Meters usage, applies rate limits, and aggregates resource telemetry.',
    description: 'Microdictyon is a high-throughput API gateway and rate-limiting sentinel that protects microservices from DDoS, throttles abuse, and meters API consumption.',
    iconUrl: 'https://cdn.infortts.site/icons/microdictyon.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.microdictyon',
    repoPath: 'projects/microdictyon',
    latest: {'android': '1.1.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.1.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/microdictyon/microdictyon.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'spriggina',
    name: 'Spriggina',
    packageName: 'com.infortts.spriggina',
    category: 'Security & IAM',
    tagline: 'Biometric identity, profile sync, and unified auth for the whole mesh.',
    description: 'Spriggina provides distributed decentralized identity management, biometric profile sync, and zero-knowledge proof credentials across all Infortts nodes.',
    iconUrl: 'https://cdn.infortts.site/icons/spriggina.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.spriggina',
    repoPath: 'projects/spriggina',
    latest: {'android': '1.1.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.1.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/spriggina/spriggina.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'tribrachidium',
    name: 'Tribrachidium',
    packageName: 'com.infortts.tribrachidium',
    category: 'Creative & Media',
    tagline: 'Distributes design tokens so every client stays in sync.',
    description: 'Tribrachidium is a design token engine that synchronizes color schemes, typography, spacing scales, and UI component definitions across Web, Android, iOS, and desktop apps.',
    iconUrl: 'https://cdn.infortts.site/icons/tribrachidium.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.tribrachidium',
    repoPath: 'projects/tribrachidium',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/tribrachidium/tribrachidium.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'trilobite',
    name: 'Trilobite Forensics',
    packageName: 'com.infortts.trilobite',
    category: 'Trading & FinTech',
    tagline: 'Tracks order flow anomalies and flags market irregularities.',
    description: 'Trilobite Forensics is a financial market microstructure analyzer and order-book forensic investigator. It processes high-frequency market depth feeds to detect spoofing, wash-trading, and algorithmic liquidity drains in real time.',
    iconUrl: 'https://cdn.infortts.site/icons/trilobite.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.trilobite',
    repoPath: 'projects/trilobite',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/trilobite/trilobite.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'wiwaxia',
    name: 'Wiwaxia',
    packageName: 'com.infortts.wiwaxia',
    category: 'Security & IAM',
    tagline: 'Hardware-backed key store and cryptographic signing vault.',
    description: 'Wiwaxia is a zero-trust cryptographic vault that manages master keys, hardware security modules (HSM), and biometric credential signing.',
    iconUrl: 'https://cdn.infortts.site/icons/wiwaxia.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.wiwaxia',
    repoPath: 'projects/wiwaxia',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/wiwaxia/wiwaxia.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'hallucigenia',
    name: 'Hallucigenia',
    packageName: 'com.infortts.hallucigenia',
    category: 'Multi-Agent AI',
    tagline: 'Generative creative engine for procedural asset and audio generation.',
    description: 'Hallucigenia is a procedural generation and generative AI audio-visual synthesizer. It creates 3D assets, textures, and adaptive soundscapes.',
    iconUrl: 'https://cdn.infortts.site/icons/hallucigenia.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.hallucigenia',
    repoPath: 'projects/hallucigenia',
    latest: {'android': '1.1.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.1.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/hallucigenia/hallucigenia.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'lexi',
    name: 'Lexi',
    packageName: 'com.infortts.lexi',
    category: 'Multi-Agent AI',
    tagline: 'Vector embeddings and fast similarity retrieval on local text.',
    description: 'Lexi is an on-device semantic search and natural language embedding library that enables vector search over documents, source code, and conversations without external APIs.',
    iconUrl: 'https://cdn.infortts.site/icons/lexi.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.lexi',
    repoPath: 'projects/lexi',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/lexi/lexi.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'cursus',
    name: 'Cursus',
    packageName: 'com.infortts.cursus',
    category: 'Infrastructure',
    tagline: 'Automates multi-step event triggers and reactive data pipelines.',
    description: 'Cursus connects webhooks, system alerts, and agent triggers into visual reactive execution graphs with conditional branching and automated retries.',
    iconUrl: 'https://cdn.infortts.site/icons/cursus.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.cursus',
    repoPath: 'projects/cursus',
    latest: {'android': '0.3.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '0.3.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/cursus/cursus.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'glycocalyx',
    name: 'Glycocalyx IAM',
    packageName: 'com.infortts.glycocalyx',
    category: 'Security & IAM',
    tagline: 'Unified IAM gateway, Google SSO, and multi-account switcher.',
    description: 'Glycocalyx is the unified authentication and Identity & Access Management gateway for the entire Infortts ecosystem. It provides Google SSO, fast multi-account switching, RBAC permissions, and JWT token issuance without forced passkey barriers.',
    iconUrl: 'https://cdn.infortts.site/icons/glycocalyx.png',
    homepageUrl: 'https://play.google.com/apps/internaltest/4701690297526834866',
    repoPath: 'projects/glycocalyx',
    latest: {'android': '2.02.00'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '2.02.00',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/glycocalyx/glycocalyx.apk',
        sha256: '',
        sizeBytes: 53900000,
        releaseNotes: [
          '✓ Sovereign IAM multi-tenant token sync',
          '✓ Google SSO and fast account switching',
          '✓ Zero passkey barrier & Direct Login'
        ],
        publishedAt: '2026-10-06T12:00:00Z',
        buildNumber: 20200,
      ),
    ],
  ),
  const AppInfo(
    slug: 'parvancorina',
    name: 'Parvancorina',
    packageName: 'com.infortts.parvancorina',
    category: 'Analytics',
    tagline: 'Lightweight UDP telemetry beacon and network ping daemon.',
    description: 'Parvancorina is an ultra-lightweight telemetry beacon and heartbeat daemon that monitors network latency, packet loss, and jitter across mesh nodes.',
    iconUrl: 'https://cdn.infortts.site/icons/parvancorina.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.parvancorina',
    repoPath: 'projects/parvancorina',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/parvancorina/parvancorina.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'kimberella',
    name: 'Kimberella Mobile',
    packageName: 'com.infortts.kimberella',
    category: 'Infrastructure',
    tagline: 'Encrypted offline note taking, PDF parsing, and document sync.',
    description: 'Kimberella is a privacy-first document editor and PDF intelligence tool that synchronizes encrypted notes and documents across devices via P2P mesh.',
    iconUrl: 'https://cdn.infortts.site/icons/kimberella.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.kimberella',
    repoPath: 'projects/kimberella',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/kimberella/kimberella.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
  const AppInfo(
    slug: 'care4u',
    name: 'Care4U Health',
    packageName: 'com.infortts.care4u',
    category: 'Healthcare',
    tagline: 'Patient vitals monitoring, appointment booking, and encrypted health records.',
    description: 'Care4U Health is a secure telehealth and bio-telemetry platform that tracks continuous biometric vitals, automates medical scheduling, and protects health records with HIPAA-grade encryption.',
    iconUrl: 'https://cdn.infortts.site/icons/care4u.png',
    homepageUrl: 'https://play.google.com/apps/testing/com.infortts.care4u',
    repoPath: 'projects/care4u',
    latest: {'android': '1.2.0'},
    versions: [
      AppVersion(
        platform: 'android',
        version: '1.2.0',
        downloadUrl: 'https://huggingface.co/datasets/rttss/ota-patches/resolve/main/care4u/care4u.apk',
        sha256: '',
        sizeBytes: 45000000,
        releaseNotes: ['Google Play internal test release.'],
        publishedAt: '2026-09-19T00:00:00Z',
        buildNumber: 1,
      ),
    ],
  ),
];
